### ISSUE TITLE
Is it actually correct that PyMongo requires the setName to connect to a Replica Set?

### ISSUE THREAD

**Issue by alitoufighi** [mongodb/specifications#801]
Is the statement mentioned in [this section](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#initial-topologytype) about _PyMongo requires replicaSet parameter to find out it is going to connect to a Replica Set_ actually valid? That spec says:

> PyMongo requires a non-null setName in order to begin replica-set monitoring, regardless of the number of seeds.

Using `pymongo==3.10.1` on Python 3.7.5, this is what I tried to see what is the real behavior:
![image](https://user-images.githubusercontent.com/30089812/81484149-bb936d80-9258-11ea-9e3f-146abbc197a6.png)

Does this mean that while not setting the `setName`, the driver understands it is connecting to a Replica Set, thus setting the `primary` attribute?

**Comment by behackett** [comment]
When not passing the replicaSet parameter PyMongo treats a single host as a server to connect directly to. It does not attempt to discover the other members of the replica set. You might want to do that if you want to use a specific secondary for expensive read operations.

Note that this is about to change in https://jira.mongodb.org/browse/PYTHON-2121 due to the spec changes in https://github.com/mongodb/specifications/commit/e56f5eceed7729f8b9b43a4a1f76c7e5840db49f.

**Comment by alitoufighi** [comment]
@behackett Thanks, so you're saying while currently the number of seeds matters, after introducing the new `directConnection` parameter, PyMongo clients must use this if they're going to connect to a Replica Set?

**Comment by behackett** [comment]
We're introducing the directConnection URI option in the next PyMongo release. We'll change the default behavior in PyMongo 4.0.

**Comment by behackett** [comment]
See the directConnection option documented in "Parameters" here:
https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient
